language: java

git:
  depth: false

dist: trusty

os:
  - linux

jdk:
  - openjdk11

env:
  - NODE_VERSION="15"

before_install:
  - nvm install $NODE_VERSION

addons:
  sonarcloud:
    organization: "foacs"
    token: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)
