export default {
    LOG_USER_IN: 'LOG_USER_IN',
    LOG_USER_OUT: 'LOG_USER_OUT',
    GET_CONTACTS: 'GET_CONTACTS',
    GET_CONTACT_BY_ID: 'GET_CONTACT_BY_ID',
    SEARCH_CONTACTS: 'SEARCH_CONTACTS',
    SAVE_CONTACT: 'SAVE_CONTACT',
    UPDATE_CONTACT_BY_ID: 'UPDATE_CONTACT_BY_ID',
    UPDATE_CONTACT_PICTURE_BY_ID: 'UPDATE_CONTACT_PICTURE_BY_ID',
    DELETE_CONTACT_BY_ID: 'DELETE_CONTACT_BY_ID'
};
