export default {
    GET_INTERVENTIONS: 'GET_INTERVENTIONS',
    GET_INTERVENTIONS_ERROR: 'GET_INTERVENTIONS_ERROR',
    GET_INTERVENTIONS_NO_CONTENT: 'GET_INTERVENTIONS_NO_CONTENT',
    GET_INTERVENTIONS_OK: 'GET_INTERVENTIONS_OK'
};
