export default {
    CHANGE_INTERVENTIONS_SORT_ORDER: 'CHANGE_INTERVENTIONS_SORT_ORDER',
    GET_INTERVENTIONS: 'GET_INTERVENTIONS',
    GET_INTERVENTIONS_ERROR: 'GET_INTERVENTIONS_ERROR',
    GET_INTERVENTIONS_NO_CONTENT: 'GET_INTERVENTIONS_NO_CONTENT',
    GET_INTERVENTIONS_OK: 'GET_INTERVENTIONS_OK'
};
