export const LOG_USER_IN = 'LOG_USER_IN';
export const LOG_USER_OUT = 'LOG_USER_OUT';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACT_BY_ID = 'GET_CONTACT_BY_ID';
export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
export const SAVE_CONTACT = 'SAVE_CONTACT';
export const UPDATE_CONTACT_BY_ID = 'UPDATE_CONTACT_BY_ID';
export const UPDATE_CONTACT_PICTURE_BY_ID = 'UPDATE_CONTACT_PICTURE_BY_ID';
export const DELETE_CONTACT_BY_ID = 'DELETE_CONTACT_BY_ID';
