export default {
    GET_CARS: 'GET_CARS',
    GET_CARS_OK: 'GET_CARS_OK',
    GET_CARS_ERROR: 'GET_CARS_ERROR',
    ADD_CAR: 'ADD_CAR',
    ADD_CAR_OK: 'ADD_CAR_OK',
    ADD_CAR_ERROR: 'ADD_CAR_ERROR',
    EDIT_CAR: 'EDIT_CAR',
    EDIT_CAR_OK: 'EDIT_CAR_OK',
    EDIT_CAR_ERROR: 'EDIT_CAR_ERROR',
    DELETE_CAR: 'DELETE_CAR',
    DELETE_CAR_OK: 'DELETE_CAR_OK',
    DELETE_CAR_ERROR: 'DELETE_CAR_ERROR',
    CHANGE_CARS_SORT_ORDER: 'CHANGE_CARS_SORT_ORDER'
};
