export default {
    CREATE_CAR: 'CREATE_CAR',
    CREATE_CAR_ERROR: 'CREATE_CAR_ERROR',
    CREATE_CAR_OK: 'CREATE_CAR_OK',
    DELETE_CAR: 'DELETE_CAR',
    DELETE_CAR_ERROR: 'DELETE_CAR_ERROR',
    DELETE_CAR_OK: 'DELETE_CAR_OK',
    GET_CAR_BY_ID: 'GET_CAR_BY_ID',
    GET_CAR_BY_ID_ERROR: 'GET_CAR_BY_ID_ERROR',
    GET_CAR_BY_ID_NOT_FOUND: 'GET_CAR_BY_ID_NOT_FOUND',
    GET_CAR_BY_ID_OK: 'GET_CAR_BY_ID_OK',
    GET_CARS: 'GET_CARS',
    GET_CARS_ERROR: 'GET_CARS_ERROR',
    GET_CARS_NO_CONTENT: 'GET_CARS_NO_CONTENT',
    GET_CARS_OK: 'GET_CARS_OK',
    UPDATE_CAR: 'UPDATE_CAR',
    UPDATE_CAR_ERROR: 'UPDATE_CAR_ERROR',
    UPDATE_CAR_OK: 'UPDATE_CAR_OK'
};
